//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasinmazMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILGI
    {
        public int ID { get; set; }
        public string ADA { get; set; }
        public string PARSEL { get; set; }
        public string NITELIK { get; set; }
        public string ADRES { get; set; }
        public Nullable<int> MAHID { get; set; }
        public Nullable<int> KULID { get; set; }
    
        public virtual KULLANICI KULLANICI { get; set; }
        public virtual MAHALLE MAHALLE { get; set; }
    }
}
