//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasinmazMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ILCE()
        {
            this.SEMT = new HashSet<SEMT>();
        }
    
        public string AD { get; set; }
        public int ILID { get; set; }
        public int ID { get; set; }
    
        public virtual IL IL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEMT> SEMT { get; set; }
    }
}
