//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasinmazMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IPAddress { get; set; }
        public string UrlAccessed { get; set; }
        public string Data { get; set; }
        public Nullable<double> ExecutionMs { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual KULLANICI KULLANICI { get; set; }
    }
}
